version: 2
jobs:
 build:
   working_directory: ~/repo
   machine: true
   branches:
    only:
      - main
   steps:
     - checkout
     - run: docker login repo.treescale.com -u $DOCKER_USER -p $DOCKER_PASS
     - run:
        name: build docker image
        command: |
            echo "deploying to development environment"
            docker build -t my-app .
            docker tag my-app repo.treescale.com/kane-99/my-app-dev:latest
            docker push repo.treescale.com/kane-99/my-app-dev:latest